## Purpose of the Notebook

Purporse of this notebook, is to create the dataframe of projects with their features

In [49]:
import pandas as pd
# File path
file_path = r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING'

# Files
file_path_CP_2 = 'RO.xlsx'

# Full import statement
sheet_mapping = 'Budget Cost'
df_project = pd.read_excel(fr'{file_path}\{file_path_CP_2}', sheet_name=sheet_mapping )

# make first row as header
df_project.columns = df_project.iloc[0]
df_project = df_project[1:]

# remove the last 6 columns
df_project = df_project.iloc[:, :-6]


# remove missing value in the column cantidad
df_project = df_project[df_project['Cantidad'].notna()]

df_project

,Activity,Cantidad,Price,Cost,Code,Cost account,Unit pctg Labour,Unit pctg Mat,Unit pctg Eq.,unit cost Labour,unit cost Mat,unit cost Eq.,subtotal Labour,subtotal Mat,subtotal Eq.,Activity Name,Planned Start,Planned Finish
2,Activity 1,1,80000,80000,C-100,Cost account 1,0,1,0,0,80000,0,0,80000,0,CARTEL PARA LA OBRA DE 3.60X2.40M.,2026-05-06 00:00:00,2026-05-26 00:00:00
3,Activity 2,1,50000,50000,C-100,Cost account 1,0,1,0,0,50000,0,0,50000,0,ALQUILER DE VIVIENDA PARA OFICINA Y ALMACÉN,2026-05-27 00:00:00,2026-06-09 00:00:00
4,Activity 3,1,50000,50000,C-100,Cost account 1,0,0,1,0,0,50000,0,0,50000,MOVILIZACION Y DESMOVILIZACION DE EQUIPO_x000D_\n,2026-05-27 00:00:00,2026-06-09 00:00:00
6,Activity 4,2400,14,33600,C-100,Cost account 1,0.970359,0,0.029641,13.585022,0,0.414978,32604.051691,0,995.948309,LIMPIEZA DE TERRENO MANUAL,2026-06-10 00:00:00,2026-06-23 00:00:00
7,Activity 5,6000,14,84000,C-100,Cost account 1,0.36508,0.571427,0.063493,5.11112,7.999973,0.888907,30666.719821,47999.840536,5333.439643,TRAZO Y REPLANTEO INICIALES DEL PROYECTO,2026-06-24 00:00:00,2026-07-07 00:00:00
9,Activity 6,14000,12,168000,C-200,Cost account 2,0.396761,0,0.603239,4.761131,0,7.238869,66655.832747,0,101344.167253,EXCAVACION MASIVA CON MAQUINA,2026-07-08 00:00:00,2026-07-28 00:00:00
10,Activity 7,8000,35,280000,C-200,Cost account 2,0.754266,0.011289,0.234445,26.399315,0.395116,8.20557,211194.517423,3160.926066,65644.556511,RELLENO COMPACTADO CON MATERIAL PROPIO,2026-08-26 00:00:00,2026-09-08 00:00:00
11,Activity 8,750,70,52500,C-200,Cost account 2,0.41856,0.451341,0.130099,29.299179,31.593862,9.106959,21974.384358,23695.396609,6830.219032,RELLENO COMPACTADO CON MATERIAL DE PRESTAMO,2026-08-26 00:00:00,2026-09-15 00:00:00
14,Activity 9,200,25,5000,C-300,Cost account 3,0.611497,0.312114,0.076389,15.287423,7.802855,1.909722,3057.484568,1560.570988,381.944444,SOLADO DE CONCRETO PARA ZAPATAS MEZCLA 1:12 (e...,2026-07-29 00:00:00,2026-08-04 00:00:00
16,Activity 10,5000,45,225000,C-400,Cost account 4,0.508906,0.475827,0.015267,22.90076,21.41221,0.687031,114503.797824,107061.047577,3435.154599,ENCOFRADO Y DESENCOFRADO NORMAL PARA MUROS DE ...,2026-08-05 00:00:00,2026-08-18 00:00:00
17,Activity 11,750,50,37500,C-400,Cost account 4,0.554367,0.428995,0.016638,27.718351,21.449744,0.831906,20788.763071,16087.30766,623.929269,ENCOFRADO Y DESENCOFRADO NORMAL EN ZAPATAS DE ...,2026-08-05 00:00:00,2026-08-11 00:00:00
18,Activity 12,1100,55,60500,C-300,Cost account 3,0.521077,0.428844,0.050079,28.659231,23.586409,2.75436,31525.154121,25945.049493,3029.796386,CONCRETO CICLOPEO 30%PM PARA MUROS f'c=140 kg/m2,2026-08-19 00:00:00,2026-08-25 00:00:00

In [50]:
df = df_project.copy()  
import re
# Clean the headers
def clean_headers(headers):
    cleaned_headers = []
    for header in headers:
        # Replace non-letter characters with underscores
        cleaned_header = re.sub(r'[^a-zA-Z0-9]', '_', header)
        cleaned_headers.append(cleaned_header)
    return cleaned_headers

# Get the original headers
original_headers = df.columns.tolist()

# Clean the headers
cleaned_headers = clean_headers(original_headers)

# Rename the columns
df.columns = cleaned_headers

# Connect to SQLite database (or create it if it doesn't exist)
# Load a sheet into a DataFrame
df

,Activity,Cantidad,Price,Cost,Code,Cost_account,Unit_pctg_Labour,Unit_pctg_Mat,Unit_pctg_Eq_,unit_cost_Labour,unit_cost_Mat,unit_cost_Eq_,subtotal_Labour,subtotal_Mat,subtotal_Eq_,Activity_Name,Planned_Start,Planned_Finish
2,Activity 1,1,80000,80000,C-100,Cost account 1,0,1,0,0,80000,0,0,80000,0,CARTEL PARA LA OBRA DE 3.60X2.40M.,2026-05-06 00:00:00,2026-05-26 00:00:00
3,Activity 2,1,50000,50000,C-100,Cost account 1,0,1,0,0,50000,0,0,50000,0,ALQUILER DE VIVIENDA PARA OFICINA Y ALMACÉN,2026-05-27 00:00:00,2026-06-09 00:00:00
4,Activity 3,1,50000,50000,C-100,Cost account 1,0,0,1,0,0,50000,0,0,50000,MOVILIZACION Y DESMOVILIZACION DE EQUIPO_x000D_\n,2026-05-27 00:00:00,2026-06-09 00:00:00
6,Activity 4,2400,14,33600,C-100,Cost account 1,0.970359,0,0.029641,13.585022,0,0.414978,32604.051691,0,995.948309,LIMPIEZA DE TERRENO MANUAL,2026-06-10 00:00:00,2026-06-23 00:00:00
7,Activity 5,6000,14,84000,C-100,Cost account 1,0.36508,0.571427,0.063493,5.11112,7.999973,0.888907,30666.719821,47999.840536,5333.439643,TRAZO Y REPLANTEO INICIALES DEL PROYECTO,2026-06-24 00:00:00,2026-07-07 00:00:00
9,Activity 6,14000,12,168000,C-200,Cost account 2,0.396761,0,0.603239,4.761131,0,7.238869,66655.832747,0,101344.167253,EXCAVACION MASIVA CON MAQUINA,2026-07-08 00:00:00,2026-07-28 00:00:00
10,Activity 7,8000,35,280000,C-200,Cost account 2,0.754266,0.011289,0.234445,26.399315,0.395116,8.20557,211194.517423,3160.926066,65644.556511,RELLENO COMPACTADO CON MATERIAL PROPIO,2026-08-26 00:00:00,2026-09-08 00:00:00
11,Activity 8,750,70,52500,C-200,Cost account 2,0.41856,0.451341,0.130099,29.299179,31.593862,9.106959,21974.384358,23695.396609,6830.219032,RELLENO COMPACTADO CON MATERIAL DE PRESTAMO,2026-08-26 00:00:00,2026-09-15 00:00:00
14,Activity 9,200,25,5000,C-300,Cost account 3,0.611497,0.312114,0.076389,15.287423,7.802855,1.909722,3057.484568,1560.570988,381.944444,SOLADO DE CONCRETO PARA ZAPATAS MEZCLA 1:12 (e...,2026-07-29 00:00:00,2026-08-04 00:00:00
16,Activity 10,5000,45,225000,C-400,Cost account 4,0.508906,0.475827,0.015267,22.90076,21.41221,0.687031,114503.797824,107061.047577,3435.154599,ENCOFRADO Y DESENCOFRADO NORMAL PARA MUROS DE ...,2026-08-05 00:00:00,2026-08-18 00:00:00
17,Activity 11,750,50,37500,C-400,Cost account 4,0.554367,0.428995,0.016638,27.718351,21.449744,0.831906,20788.763071,16087.30766,623.929269,ENCOFRADO Y DESENCOFRADO NORMAL EN ZAPATAS DE ...,2026-08-05 00:00:00,2026-08-11 00:00:00
18,Activity 12,1100,55,60500,C-300,Cost account 3,0.521077,0.428844,0.050079,28.659231,23.586409,2.75436,31525.154121,25945.049493,3029.796386,CONCRETO CICLOPEO 30%PM PARA MUROS f'c=140 kg/m2,2026-08-19 00:00:00,2026-08-25 00:00:00

In [53]:
df[['Cost']].sum()

Cost    1126100
dtype: object

In [54]:
import sqlite3

# Create a database connection
conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')
cursor = conn.cursor()

# Drop the existing table if it exists
cursor.execute("DROP TABLE IF EXISTS Project_RO_table")

# Write records stored in a DataFrame to a SQL database
df_project.to_sql('Project_RO_table', conn, if_exists='replace', index=False)

# Don't forget to close the connection
conn.close()