# Purpose of the code

## PV

Easy draw the EV to_go graph for a project based on dates updated.

In [1]:
import pandas as pd
import sqlite3
from datetime import timedelta  # <-- needed for date_range with Timedelta or you can use freq='D'

conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_03 = """
SELECT *
FROM Project_RO_table

"""

df = pd.read_sql_query(query_03, conn)
conn.close()
df

,Activity,Cantidad,Price,Cost,Code,Cost account,Unit pctg Labour,Unit pctg Mat,Unit pctg Eq.,unit cost Labour,unit cost Mat,unit cost Eq.,subtotal Labour,subtotal Mat,subtotal Eq.,Activity Name,Planned Start,Planned Finish
0,Activity 1,1,80000,80000,C-100,Cost account 1,0,1,0,0,80000,0,0,80000,0,CARTEL PARA LA OBRA DE 3.60X2.40M.,2026-05-06 00:00:00,2026-05-26 00:00:00
1,Activity 2,1,50000,50000,C-100,Cost account 1,0,1,0,0,50000,0,0,50000,0,ALQUILER DE VIVIENDA PARA OFICINA Y ALMACÉN,2026-05-27 00:00:00,2026-06-09 00:00:00
2,Activity 3,1,50000,50000,C-100,Cost account 1,0,0,1,0,0,50000,0,0,50000,MOVILIZACION Y DESMOVILIZACION DE EQUIPO_x000D_\n,2026-05-27 00:00:00,2026-06-09 00:00:00
3,Activity 4,2400,14,33600,C-100,Cost account 1,0.970358681281187,0,0.0296413187188126,13.5850215379366,0,0.414978462063376,32604.0516910479,0,995.948308952103,LIMPIEZA DE TERRENO MANUAL,2026-06-10 00:00:00,2026-06-23 00:00:00
4,Activity 5,6000,14,84000,C-100,Cost account 1,0.365079997873811,0.571426673045235,0.0634933290809547,5.11111997023335,7.99997342263329,0.888906607133365,30666.7198214001,47999.8405357997,5333.43964280019,TRAZO Y REPLANTEO INICIALES DEL PROYECTO,2026-06-24 00:00:00,2026-07-07 00:00:00
5,Activity 6,14000,12,168000,C-200,Cost account 2,0.3967609092068,0,0.6032390907932,4.7611309104816,0,7.2388690895184,66655.8327467424,0,101344.167253258,EXCAVACION MASIVA CON MAQUINA,2026-07-08 00:00:00,2026-07-28 00:00:00
6,Activity 7,8000,35,280000,C-200,Cost account 2,0.754266133652828,0.0112890216638019,0.23444484468337,26.399314677849,0.395115758233067,8.20556956391794,211194.517422792,3160.92606586454,65644.5565113435,RELLENO COMPACTADO CON MATERIAL PROPIO,2026-08-26 00:00:00,2026-09-08 00:00:00
7,Activity 8,750,70,52500,C-200,Cost account 2,0.418559702064219,0.451340887796772,0.130099410139009,29.2991791444953,31.593862145774,9.10695870973064,21974.3843583715,23695.3966093305,6830.21903229798,RELLENO COMPACTADO CON MATERIAL DE PRESTAMO,2026-08-26 00:00:00,2026-09-15 00:00:00
8,Activity 9,200,25,5000,C-300,Cost account 3,0.611496913580247,0.312114197530864,0.0763888888888888,15.2874228395062,7.80285493827161,1.90972222222222,3057.48456790123,1560.57098765432,381.944444444444,SOLADO DE CONCRETO PARA ZAPATAS MEZCLA 1:12 (e...,2026-07-29 00:00:00,2026-08-04 00:00:00
9,Activity 10,5000,45,225000,C-400,Cost account 4,0.508905768106262,0.475826878118337,0.0152673537754019,22.9007595647818,21.4122095153251,0.687030919893085,114503.797823909,107061.047576626,3435.15459946543,ENCOFRADO Y DESENCOFRADO NORMAL PARA MUROS DE ...,2026-08-05 00:00:00,2026-08-18 00:00:00
10,Activity 11,750,50,37500,C-400,Cost account 4,0.554367015220048,0.428994870937751,0.0166381138422003,27.7183507610024,21.4497435468876,0.831905692110013,20788.7630707518,16087.3076601657,623.92926908251,ENCOFRADO Y DESENCOFRADO NORMAL EN ZAPATAS DE ...,2026-08-05 00:00:00,2026-08-11 00:00:00
11,Activity 12,1100,55,60500,C-300,Cost account 3,0.521076927619933,0.428843793274409,0.0500792791056583,28.6592310190963,23.5864086300925,2.75436035081121,31525.1541210059,25945.0494931017,3029.79638589233,CONCRETO CICLOPEO 30%PM PARA MUROS f'c=140 kg/m2,2026-08-19 00:00:00,2026-08-25 00:00:00

In [2]:

df[['Cost']].sum()

Cost    1126100
dtype: int64

In [3]:
df.columns.tolist()

['Activity',
 'Cantidad',
 'Price',
 'Cost',
 'Code',
 'Cost account',
 'Unit pctg Labour',
 'Unit pctg Mat',
 'Unit pctg Eq.',
 'unit cost Labour',
 'unit cost Mat',
 'unit cost Eq.',
 'subtotal Labour',
 'subtotal Mat',
 'subtotal Eq.',
 'Activity Name',
 'Planned Start',
 'Planned Finish']

In [2]:
import pandas as pd
import sqlite3
from datetime import timedelta  # <-- needed for date_range with Timedelta or you can use freq='D'

conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_03 = """
SELECT *
FROM Project_RO_table

"""

df = pd.read_sql_query(query_03, conn)
conn.close()
df

df_project = df[[
 'Activity',
 'Activity Name',
 'Planned Start',
 'Planned Finish',
 'Cost',
 'Cost account']].copy()
df.head()
df

,Activity,Cantidad,Price,Cost,Code,Cost account,Unit pctg Labour,Unit pctg Mat,Unit pctg Eq.,unit cost Labour,unit cost Mat,unit cost Eq.,subtotal Labour,subtotal Mat,subtotal Eq.,Activity Name,Planned Start,Planned Finish
0,Activity 1,1,80000,80000,C-100,Cost account 1,0,1,0,0,80000,0,0,80000,0,CARTEL PARA LA OBRA DE 3.60X2.40M.,2026-05-06 00:00:00,2026-05-26 00:00:00
1,Activity 2,1,50000,50000,C-100,Cost account 1,0,1,0,0,50000,0,0,50000,0,ALQUILER DE VIVIENDA PARA OFICINA Y ALMACÉN,2026-05-27 00:00:00,2026-06-09 00:00:00
2,Activity 3,1,50000,50000,C-100,Cost account 1,0,0,1,0,0,50000,0,0,50000,MOVILIZACION Y DESMOVILIZACION DE EQUIPO_x000D_\n,2026-05-27 00:00:00,2026-06-09 00:00:00
3,Activity 4,2400,14,33600,C-100,Cost account 1,0.970358681281187,0,0.0296413187188126,13.5850215379366,0,0.414978462063376,32604.0516910479,0,995.948308952103,LIMPIEZA DE TERRENO MANUAL,2026-06-10 00:00:00,2026-06-23 00:00:00
4,Activity 5,6000,14,84000,C-100,Cost account 1,0.365079997873811,0.571426673045235,0.0634933290809547,5.11111997023335,7.99997342263329,0.888906607133365,30666.7198214001,47999.8405357997,5333.43964280019,TRAZO Y REPLANTEO INICIALES DEL PROYECTO,2026-06-24 00:00:00,2026-07-07 00:00:00
5,Activity 6,14000,12,168000,C-200,Cost account 2,0.3967609092068,0,0.6032390907932,4.7611309104816,0,7.2388690895184,66655.8327467424,0,101344.167253258,EXCAVACION MASIVA CON MAQUINA,2026-07-08 00:00:00,2026-07-28 00:00:00
6,Activity 7,8000,35,280000,C-200,Cost account 2,0.754266133652828,0.0112890216638019,0.23444484468337,26.399314677849,0.395115758233067,8.20556956391794,211194.517422792,3160.92606586454,65644.5565113435,RELLENO COMPACTADO CON MATERIAL PROPIO,2026-08-26 00:00:00,2026-09-08 00:00:00
7,Activity 8,750,70,52500,C-200,Cost account 2,0.418559702064219,0.451340887796772,0.130099410139009,29.2991791444953,31.593862145774,9.10695870973064,21974.3843583715,23695.3966093305,6830.21903229798,RELLENO COMPACTADO CON MATERIAL DE PRESTAMO,2026-08-26 00:00:00,2026-09-15 00:00:00
8,Activity 9,200,25,5000,C-300,Cost account 3,0.611496913580247,0.312114197530864,0.0763888888888888,15.2874228395062,7.80285493827161,1.90972222222222,3057.48456790123,1560.57098765432,381.944444444444,SOLADO DE CONCRETO PARA ZAPATAS MEZCLA 1:12 (e...,2026-07-29 00:00:00,2026-08-04 00:00:00
9,Activity 10,5000,45,225000,C-400,Cost account 4,0.508905768106262,0.475826878118337,0.0152673537754019,22.9007595647818,21.4122095153251,0.687030919893085,114503.797823909,107061.047576626,3435.15459946543,ENCOFRADO Y DESENCOFRADO NORMAL PARA MUROS DE ...,2026-08-05 00:00:00,2026-08-18 00:00:00
10,Activity 11,750,50,37500,C-400,Cost account 4,0.554367015220048,0.428994870937751,0.0166381138422003,27.7183507610024,21.4497435468876,0.831905692110013,20788.7630707518,16087.3076601657,623.92926908251,ENCOFRADO Y DESENCOFRADO NORMAL EN ZAPATAS DE ...,2026-08-05 00:00:00,2026-08-11 00:00:00
11,Activity 12,1100,55,60500,C-300,Cost account 3,0.521076927619933,0.428843793274409,0.0500792791056583,28.6592310190963,23.5864086300925,2.75436035081121,31525.1541210059,25945.0494931017,3029.79638589233,CONCRETO CICLOPEO 30%PM PARA MUROS f'c=140 kg/m2,2026-08-19 00:00:00,2026-08-25 00:00:00

In [3]:
import pandas as pd
import sqlite3
from datetime import timedelta  # <-- needed for date_range with Timedelta or you can use freq='D'

conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_03 = """
SELECT *
FROM Project_RO_table

"""

df = pd.read_sql_query(query_03, conn)
conn.close()
df

df_project = df[[
 'Activity',
 'Activity Name',
 'Planned Start',
 'Planned Finish',
 'Cost',
 'Cost account']].copy()
df.head()
df
df_act = df_project.rename(columns={
    'Activity': 'Activity_ID',
    'Cost account':'COA',
    'Activity Name': 'Activity_Description',
    'Planned Start': 'Start_Date',
    'Planned Finish': 'End_Date',
    'Cost': 'BAC',
})  

# Set the start of the upcoming month
df_act ['Today'] = '01/05/2026'

public_holidays = pd.to_datetime([
    '2026-01-01',  # New Year’s Day
    '2026-04-02',  # Maundy Thursday
    '2026-04-03',  # Good Friday
    '2026-05-01',  # Labour Day
    '2026-06-07',  # Battle of Arica & Flag Day (often observed together)
    '2026-06-29',  # Saints Peter and Paul
    '2026-07-23',  # Air Force Day
    '2026-07-28',  # Independence Day
    '2026-07-29',  # Independence Day (second day)
    '2026-08-06',  # Battle of Junín
    '2026-08-30',  # Santa Rosa de Lima
    '2026-10-08',  # Battle of Angamos
    '2026-11-01',  # All Saints’ Day
    '2026-12-08',  # Immaculate Conception
    '2026-12-09',  # Battle of Ayacucho
    '2026-12-25',  # Christmas Day
])


# Ensure the date columns are date type
df_act['BAC'] = df_act['BAC'].astype(float)
df_act['Start_Date'] = pd.to_datetime(df_act['Start_Date'] , errors='coerce')
df_act['End_Date'] = pd.to_datetime(df_act['End_Date'] , errors='coerce')
df_act['Today'] = pd.to_datetime(df_act['Today'] , errors='coerce')

# Ensure that the start date is greater or equals than the start of next month
df_act['Start_Date'] = df_act.apply(lambda row: row['Start_Date'] if row['Start_Date'] > row['Today'] else row['Today'], axis=1)

# Ensure that the end date is greater or equals than the start of next month
df_act['End_Date'] = df_act.apply(lambda row: row['End_Date'] if row['End_Date'] > row['Today'] else row['Today'], axis=1)


#df, cost_column, start_column, end_column = df_CP_EV_togo, 'Etc', 'Start_mapping','End_mapping'
df, cost_column, start_column, end_column = df_act, 'BAC', 'Start_Date','End_Date'

df[end_column] = pd.to_datetime(df[end_column], errors='coerce')
df[start_column] = pd.to_datetime(df[start_column], errors='coerce')
df['Duration'] = (df[end_column] - df[start_column]).dt.days + 1

# Build the effective working-date range first so holidays only redistribute value.
df['Date_Range'] = df.apply(
  lambda row: [
    d for d in pd.date_range(start=row[start_column], end=row[end_column], freq='D').tolist()
    if d not in public_holidays
  ],
  axis=1
)
df['Effective_Days'] = df['Date_Range'].str.len()
df = df[df['Effective_Days'] > 0].copy()

# Allocate BAC across effective days so the monthly rollup preserves the total.
df['PV per day'] = df[cost_column] / df['Effective_Days']

# Define the step as a timedelta of 1 day
step = timedelta(days=1)

# Explode the 'Date_Range' column into separate rows
df_exploded = df.explode('Date_Range')

# Add a new column 'Start_Month' with the start of the month for each date in 'Date_Range'
df_exploded['Start_Month'] = df_exploded['Date_Range'].dt.to_period('M').dt.to_timestamp()
df_exploded


# Group by 'Activity_ID' and 'Start_Month' to sum the effective daily value
df_monthly = df_exploded.groupby(['COA','Activity_ID',  'Activity_Description','Start_Month'], as_index=False)['PV per day'].sum()
df_monthly

df_monthly ['evm_type'] = 'pv'

df_monthly= df_monthly.rename(columns={
    'Start_Month': 'Data_Date',
    'PV per day': 'EVM_value'
})

df_monthly['EVM_value'].sum()

#export to excel
#df_monthly.to_excel(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\df_monthly.xlsx', index=False)

1126100.0

In [4]:
df_monthly_pv = df_monthly.groupby(['COA','Data_Date', 'evm_type'], as_index=False)['EVM_value'].sum()
df_monthly_pv

              COA  Data_Date evm_type      EVM_value
0  Cost account 1 2026-05-01       pv  118461.538462
1  Cost account 1 2026-06-01       pv  133907.692308
2  Cost account 1 2026-07-01       pv   45230.769231
3  Cost account 2 2026-07-01       pv  168000.000000
4  Cost account 2 2026-08-01       pv  120817.307692
5  Cost account 2 2026-09-01       pv  211682.692308
6  Cost account 3 2026-07-01       pv    1666.666667
7  Cost account 3 2026-08-01       pv   63833.333333
8  Cost account 4 2026-08-01       pv  262500.000000

### Save Monthly PV time Phased

In [5]:
import sqlite3

table_name = "COA_monthly_pv_table"
print(table_name)

# Connect
conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')
cursor = conn.cursor()

# Drop table
cursor.execute(f"DROP TABLE IF EXISTS {table_name}")

# Write DataFrame
df_monthly_pv.to_sql(table_name, conn, if_exists='replace', index=False)

# Close
conn.close()

COA_monthly_pv_table

# Compute PV cummulative by coa and period

In [ ]:
# unpivot the DataFrame to have 'evm_type' as columns
df_pivot = df_monthly_pv.pivot_table(index=['COA', 'Data_Date'], columns='evm_type', values='EVM_value', fill_value=0).reset_index()
df_pivot

evm_type             COA  Data_Date             pv
0         Cost account 1 2026-05-01  118461.538462
1         Cost account 1 2026-06-01  133907.692308
2         Cost account 1 2026-07-01   45230.769231
3         Cost account 2 2026-07-01  168000.000000
4         Cost account 2 2026-08-01  120817.307692
5         Cost account 2 2026-09-01  211682.692308
6         Cost account 3 2026-07-01    1666.666667
7         Cost account 3 2026-08-01   63833.333333
8         Cost account 4 2026-08-01  262500.000000

In [15]:
# compute pv cumulative
project_end_date = df_pivot['Data_Date'].max()
full_dates = pd.date_range(df_pivot['Data_Date'].min(), project_end_date, freq='MS')
all_coas = df_pivot['COA'].drop_duplicates()
full_index = pd.MultiIndex.from_product([all_coas, full_dates], names=['COA', 'Data_Date'])
df_pivot = (
    df_pivot.set_index(['COA', 'Data_Date'])
    .reindex(full_index, fill_value=0)
    .reset_index()
)
df_pivot['PV_Cumulative'] = df_pivot.groupby('COA')['pv'].cumsum()

# rename Data_Date to Period
df_pivot = df_pivot.rename(columns={'Data_Date': 'Period'})
df_pivot

evm_type             COA     Period             pv  PV_Cumulative
0         Cost account 1 2026-05-01  118461.538462  118461.538462
1         Cost account 1 2026-06-01  133907.692308  252369.230769
2         Cost account 1 2026-07-01   45230.769231  297600.000000
3         Cost account 1 2026-08-01       0.000000  297600.000000
4         Cost account 1 2026-09-01       0.000000  297600.000000
5         Cost account 2 2026-05-01       0.000000       0.000000
6         Cost account 2 2026-06-01       0.000000       0.000000
7         Cost account 2 2026-07-01  168000.000000  168000.000000
8         Cost account 2 2026-08-01  120817.307692  288817.307692
9         Cost account 2 2026-09-01  211682.692308  500500.000000
10        Cost account 3 2026-05-01       0.000000       0.000000
11        Cost account 3 2026-06-01       0.000000       0.000000
12        Cost account 3 2026-07-01    1666.666667    1666.666667
13        Cost account 3 2026-08-01   63833.333333   65500.000000
14        Cost account 3 2026-09-01       0.000000   65500.000000
15        Cost account 4 2026-05-01       0.000000       0.000000
16        Cost account 4 2026-06-01       0.000000       0.000000
17        Cost account 4 2026-07-01       0.000000       0.000000
18        Cost account 4 2026-08-01  262500.000000  262500.000000
19        Cost account 4 2026-09-01       0.000000  262500.000000

In [16]:
import sqlite3

table_name = "COA_pv_cumulative_table"
print(table_name)

# Connect
conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')
cursor = conn.cursor()

# Drop table
cursor.execute(f"DROP TABLE IF EXISTS {table_name}")

# Write DataFrame
df_pivot.to_sql(table_name, conn, if_exists='replace', index=False)

# Close
conn.close()

COA_pv_cumulative_table

In [7]:
summary_check = pd.DataFrame({
    'budget_sum': [df_act['BAC'].sum()],
    'monthly_sum': [df_monthly['EVM_value'].sum()],
    'difference': [df_act['BAC'].sum() - df_monthly['EVM_value'].sum()],
    'holiday_loss_unrounded': [((df['BAC'] / df['Duration']) * (df['Duration'] - df['Date_Range'].str.len())).sum()],
    'holiday_days_removed': [(df['Duration'] - df['Date_Range'].str.len()).sum()],
    'rounding_effect': [((df['BAC'] / df['Duration']).round(2) * df['Date_Range'].str.len()).sum() - ((df['BAC'] / df['Duration']) * df['Date_Range'].str.len()).sum()],
})
summary_check

,budget_sum,monthly_sum,difference,holiday_loss_unrounded,holiday_days_removed,rounding_effect
0,1126100.0,1126100.0,0.0,73785.714286,10,0.004286