Purpose of the script

Compute EVM metrics and time phased values

# Cumulative Variances

In [1]:
import pandas as pd
import sqlite3
from datetime import timedelta  # <-- needed for date_range with Timedelta or you can use freq='D'

conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_01 = """
SELECT *
FROM period_2026_05

"""

df = pd.read_sql_query(query_01, conn)
conn.close()
df

conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_01A = """
SELECT *
FROM period_2026_06

"""

dfA = pd.read_sql_query(query_01A, conn)
conn.close()
dfA

,COA,Activity,Unit,Quantity,Budget,Start,Finish,Actual qty,EV,EV (Cost account),AC,ETC,EAC,Period
0,Cost account 1,None,None,NaN,NaN,None,None,NaN,NaN,222000.0,239760.0,66768.0,306528.0,2026-06-01 00:00:00
1,Cost account 1,Activity 1,%,1.0,80000.0,2026-05-06 00:00:00,2026-05-26 00:00:00,1.0,80000.0,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
2,Cost account 1,Activity 2,%,1.0,50000.0,2026-05-27 00:00:00,2026-06-09 00:00:00,1.0,50000.0,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
3,Cost account 1,Activity 3,%,1.0,50000.0,2026-05-27 00:00:00,2026-06-09 00:00:00,1.0,50000.0,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
4,Cost account 1,Activity 4,m2,2400.0,33600.0,2026-06-10 00:00:00,2026-06-23 00:00:00,1.0,33600.0,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
5,Cost account 1,Activity 5,m2,6000.0,84000.0,2026-06-24 00:00:00,2026-07-07 00:00:00,0.1,8400.0,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
6,Cost account 2,None,None,NaN,NaN,None,None,NaN,NaN,0.0,0.0,520520.0,520520.0,2026-06-01 00:00:00
7,Cost account 2,Activity 6,m3,14000.0,168000.0,2026-07-08 00:00:00,2026-07-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
8,Cost account 2,Activity 7,m3,8000.0,280000.0,2026-08-26 00:00:00,2026-09-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
9,Cost account 2,Activity 8,m3,750.0,52500.0,2026-08-26 00:00:00,2026-09-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
10,Cost account 3,None,None,NaN,NaN,None,None,NaN,NaN,0.0,0.0,70100.0,70100.0,2026-06-01 00:00:00
11,Cost account 3,Activity 12,m3,1100.0,60500.0,2026-08-19 00:00:00,2026-08-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
12,Cost account 3,Activity 9,m2,200.0,5000.0,2026-07-29 00:00:00,2026-08-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
13,Cost account 4,None,None,NaN,NaN,None,None,NaN,NaN,0.0,0.0,273000.0,273000.0,2026-06-01 00:00:00
14,Cost account 4,Activity 10,m2,5000.0,225000.0,2026-08-05 00:00:00,2026-08-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-01 00:00:00
15,Cost account 4,Activity 11,m3,750.0,37500.0,2026-08-05 00:00:00,2026-08-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-01 00:00:00

In [2]:
appended_df = pd.concat([df, dfA], ignore_index=True)

In [3]:
grouped = appended_df.groupby(['COA', 'Period']).agg({'Budget': 'sum', 'EV': 'sum', 'AC': 'sum','ETC':'sum','EAC': 'sum'}).reset_index()
grouped

,COA,Period,Budget,EV,AC,ETC,EAC
0,Cost account 1,2026-05-01 00:00:00,297600.0,118000.0,127440.0,179088.0,306528.0
1,Cost account 1,2026-06-01 00:00:00,297600.0,222000.0,239760.0,66768.0,306528.0
2,Cost account 2,2026-05-01 00:00:00,500500.0,0.0,0.0,520520.0,520520.0
3,Cost account 2,2026-06-01 00:00:00,500500.0,0.0,0.0,520520.0,520520.0
4,Cost account 3,2026-05-01 00:00:00,65500.0,0.0,0.0,70100.0,70100.0
5,Cost account 3,2026-06-01 00:00:00,65500.0,0.0,0.0,70100.0,70100.0
6,Cost account 4,2026-05-01 00:00:00,262500.0,0.0,0.0,273000.0,273000.0
7,Cost account 4,2026-06-01 00:00:00,262500.0,0.0,0.0,273000.0,273000.0

In [4]:
conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_02 = """
SELECT *
FROM COA_pv_cumulative_table

"""

df_PV = pd.read_sql_query(query_02, conn)
conn.close()
# Merge dataframes on 'Cost account' and 'Period'

df_PV

               COA               Period             pv  PV_Cumulative
0   Cost account 1  2026-05-01 00:00:00  118461.538462  118461.538462
1   Cost account 1  2026-06-01 00:00:00  133907.692308  252369.230769
2   Cost account 1  2026-07-01 00:00:00   45230.769231  297600.000000
3   Cost account 1  2026-08-01 00:00:00       0.000000  297600.000000
4   Cost account 1  2026-09-01 00:00:00       0.000000  297600.000000
5   Cost account 2  2026-05-01 00:00:00       0.000000       0.000000
6   Cost account 2  2026-06-01 00:00:00       0.000000       0.000000
7   Cost account 2  2026-07-01 00:00:00  168000.000000  168000.000000
8   Cost account 2  2026-08-01 00:00:00  120817.307692  288817.307692
9   Cost account 2  2026-09-01 00:00:00  211682.692308  500500.000000
10  Cost account 3  2026-05-01 00:00:00       0.000000       0.000000
11  Cost account 3  2026-06-01 00:00:00       0.000000       0.000000
12  Cost account 3  2026-07-01 00:00:00    1666.666667    1666.666667
13  Cost account 3  2026-08-01 00:00:00   63833.333333   65500.000000
14  Cost account 3  2026-09-01 00:00:00       0.000000   65500.000000
15  Cost account 4  2026-05-01 00:00:00       0.000000       0.000000
16  Cost account 4  2026-06-01 00:00:00       0.000000       0.000000
17  Cost account 4  2026-07-01 00:00:00       0.000000       0.000000
18  Cost account 4  2026-08-01 00:00:00  262500.000000  262500.000000
19  Cost account 4  2026-09-01 00:00:00       0.000000  262500.000000

In [5]:
df_merged = pd.merge(grouped, df_PV, left_on=['COA', 'Period'], right_on=['COA', 'Period'], how='left')
df_merged

,COA,Period,Budget,EV,AC,ETC,EAC,pv,PV_Cumulative
0,Cost account 1,2026-05-01 00:00:00,297600.0,118000.0,127440.0,179088.0,306528.0,118461.538462,118461.538462
1,Cost account 1,2026-06-01 00:00:00,297600.0,222000.0,239760.0,66768.0,306528.0,133907.692308,252369.230769
2,Cost account 2,2026-05-01 00:00:00,500500.0,0.0,0.0,520520.0,520520.0,0.000000,0.000000
3,Cost account 2,2026-06-01 00:00:00,500500.0,0.0,0.0,520520.0,520520.0,0.000000,0.000000
4,Cost account 3,2026-05-01 00:00:00,65500.0,0.0,0.0,70100.0,70100.0,0.000000,0.000000
5,Cost account 3,2026-06-01 00:00:00,65500.0,0.0,0.0,70100.0,70100.0,0.000000,0.000000
6,Cost account 4,2026-05-01 00:00:00,262500.0,0.0,0.0,273000.0,273000.0,0.000000,0.000000
7,Cost account 4,2026-06-01 00:00:00,262500.0,0.0,0.0,273000.0,273000.0,0.000000,0.000000

In [6]:
df_merged['CV']= df_merged['EV'] - df_merged['AC']

df_merged['SV']= df_merged['EV'] - df_merged['PV_Cumulative']
df_merged['CPI']= df_merged['EV'] / df_merged['AC']
df_merged['SPI']= df_merged['EV'] / df_merged['PV_Cumulative']

df_merged

,COA,Period,Budget,EV,AC,ETC,EAC,pv,PV_Cumulative,CV,SV,CPI,SPI
0,Cost account 1,2026-05-01 00:00:00,297600.0,118000.0,127440.0,179088.0,306528.0,118461.538462,118461.538462,-9440.0,-461.538462,0.925926,0.996104
1,Cost account 1,2026-06-01 00:00:00,297600.0,222000.0,239760.0,66768.0,306528.0,133907.692308,252369.230769,-17760.0,-30369.230769,0.925926,0.879663
2,Cost account 2,2026-05-01 00:00:00,500500.0,0.0,0.0,520520.0,520520.0,0.000000,0.000000,0.0,0.000000,NaN,NaN
3,Cost account 2,2026-06-01 00:00:00,500500.0,0.0,0.0,520520.0,520520.0,0.000000,0.000000,0.0,0.000000,NaN,NaN
4,Cost account 3,2026-05-01 00:00:00,65500.0,0.0,0.0,70100.0,70100.0,0.000000,0.000000,0.0,0.000000,NaN,NaN
5,Cost account 3,2026-06-01 00:00:00,65500.0,0.0,0.0,70100.0,70100.0,0.000000,0.000000,0.0,0.000000,NaN,NaN
6,Cost account 4,2026-05-01 00:00:00,262500.0,0.0,0.0,273000.0,273000.0,0.000000,0.000000,0.0,0.000000,NaN,NaN
7,Cost account 4,2026-06-01 00:00:00,262500.0,0.0,0.0,273000.0,273000.0,0.000000,0.000000,0.0,0.000000,NaN,NaN

## Sending to the dataframe

In [7]:
# Send to the database
import sqlite3

table_name = "EVM_metrics"
print(table_name)

# Connect
conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')
cursor = conn.cursor()

# Drop table
cursor.execute(f"DROP TABLE IF EXISTS {table_name}")

# Write DataFrame
df_merged.to_sql(table_name, conn, if_exists='replace', index=False)

# Close
conn.close()

EVM_metrics

### test the import before reading in power BI

In [ ]:
import pandas as pd
import sqlite3
conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_03 = """
SELECT *
FROM EVM_metrics

"""

df_EVM_metrics = pd.read_sql_query(query_03, conn)
conn.close()

df_EVM_metrics

,COA,Period,Budget,EV,AC,ETC,EAC,pv,PV_Cumulative,CV,SV,CPI,SPI
0,Cost account 1,2026-05-01 00:00:00,297600.0,118000.0,127440.0,179088.0,306528.0,118461.538462,118461.538462,-9440.0,-461.538462,0.925926,0.996104
1,Cost account 2,2026-05-01 00:00:00,500500.0,0.0,0.0,520520.0,520520.0,0.000000,0.000000,0.0,0.000000,NaN,NaN
2,Cost account 3,2026-05-01 00:00:00,65500.0,0.0,0.0,70100.0,70100.0,0.000000,0.000000,0.0,0.000000,NaN,NaN
3,Cost account 4,2026-05-01 00:00:00,262500.0,0.0,0.0,273000.0,273000.0,0.000000,0.000000,0.0,0.000000,NaN,NaN

# Time phased

## EV and AC

In [9]:
import pandas as pd
import sqlite3
from datetime import timedelta  # <-- needed for date_range with Timedelta or you can use freq='D'

conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_04 = """
SELECT *
FROM period_2026_05

"""

df = pd.read_sql_query(query_04, conn)
conn.close()

conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_04A = """
SELECT *
FROM period_2026_06

"""

dfA = pd.read_sql_query(query_04A, conn)
conn.close()
appended_df = pd.concat([df, dfA], ignore_index=True)

Work with Earned Value

In [ ]:
df_ev = appended_df[['COA', 'Activity', 'Start', 'Finish', 'EV','AC','Period']]

# Aggregate EV and AC by COA and Period
df_evA = df_ev.groupby(['COA', 'Period']).agg({'EV': 'sum', 'AC': 'sum'}).reset_index()

# Calculate the difference between the current and previous period for EV and AC
df_evA['EV_shifted'] = df_evA.groupby('COA')['EV'].shift(1).fillna(0)
df_evA['AC_shifted'] = df_evA.groupby('COA')['AC'].shift(1).fillna(0)


df_evA['EV_period'] = df_evA['EV']- df_evA['EV_shifted']
df_evA['AC_period'] = df_evA['AC']- df_evA['AC_shifted']

df_evB = df_evA[['COA', 'Period', 'EV_period', 'AC_period']]

melted = df_evB.melt(id_vars=['COA', 'Period'], value_vars=['EV_period', 'AC_period'], var_name='Metric', value_name='Value')
melted

,COA,Activity,Start,Finish,EV,AC,Period
0,Cost account 1,None,None,None,NaN,127440.0,2026-05-01 00:00:00
1,Cost account 1,Activity 1,2026-05-06 00:00:00,2026-05-26 00:00:00,80000.0,NaN,2026-05-01 00:00:00
2,Cost account 1,Activity 2,2026-05-27 00:00:00,2026-06-09 00:00:00,19000.0,NaN,2026-05-01 00:00:00
3,Cost account 1,Activity 3,2026-05-27 00:00:00,2026-06-09 00:00:00,19000.0,NaN,2026-05-01 00:00:00
4,Cost account 1,Activity 4,2026-06-10 00:00:00,2026-06-23 00:00:00,NaN,NaN,2026-05-01 00:00:00
5,Cost account 1,Activity 5,2026-06-24 00:00:00,2026-07-07 00:00:00,NaN,NaN,2026-05-01 00:00:00
6,Cost account 2,None,None,None,NaN,0.0,2026-05-01 00:00:00
7,Cost account 2,Activity 6,2026-07-08 00:00:00,2026-07-28 00:00:00,NaN,NaN,2026-05-01 00:00:00
8,Cost account 2,Activity 7,2026-08-26 00:00:00,2026-09-08 00:00:00,NaN,NaN,2026-05-01 00:00:00
9,Cost account 2,Activity 8,2026-08-26 00:00:00,2026-09-15 00:00:00,NaN,NaN,2026-05-01 00:00:00
10,Cost account 3,None,None,None,NaN,0.0,2026-05-01 00:00:00
11,Cost account 3,Activity 12,2026-08-19 00:00:00,2026-08-25 00:00:00,NaN,NaN,2026-05-01 00:00:00
12,Cost account 3,Activity 9,2026-07-29 00:00:00,2026-08-04 00:00:00,NaN,NaN,2026-05-01 00:00:00
13,Cost account 4,None,None,None,NaN,0.0,2026-05-01 00:00:00
14,Cost account 4,Activity 10,2026-08-05 00:00:00,2026-08-18 00:00:00,NaN,NaN,2026-05-01 00:00:00
15,Cost account 4,Activity 11,2026-08-05 00:00:00,2026-08-11 00:00:00,NaN,NaN,2026-05-01 00:00:00
16,Cost account 1,None,None,None,NaN,239760.0,2026-06-01 00:00:00
17,Cost account 1,Activity 1,2026-05-06 00:00:00,2026-05-26 00:00:00,80000.0,NaN,2026-06-01 00:00:00
18,Cost account 1,Activity 2,2026-05-27 00:00:00,2026-06-09 00:00:00,50000.0,NaN,2026-06-01 00:00:00
19,Cost account 1,Activity 3,2026-05-27 00:00:00,2026-06-09 00:00:00,50000.0,NaN,2026-06-01 00:00:00
20,Cost account 1,Activity 4,2026-06-10 00:00:00,2026-06-23 00:00:00,33600.0,NaN,2026-06-01 00:00:00
21,Cost account 1,Activity 5,2026-06-24 00:00:00,2026-07-07 00:00:00,8400.0,NaN,2026-06-01 00:00:00
22,Cost account 2,None,None,None,NaN,0.0,2026-06-01 00:00:00
23,Cost account 2,Activity 6,2026-07-08 00:00:00,2026-07-28 00:00:00,NaN,NaN,2026-06-01 00:00:00
24,Cost account 2,Activity 7,2026-08-26 00:00:00,2026-09-08 00:00:00,NaN,NaN,2026-06-01 00:00:00
25,Cost account 2,Activity 8,2026-08-26 00:00:00,2026-09-15 00:00:00,NaN,NaN,2026-06-01 00:00:00
26,Cost account 3,None,None,None,NaN,0.0,2026-06-01 00:00:00
27,Cost account 3,Activity 12,2026-08-19 00:00:00,2026-08-25 00:00:00,NaN,NaN,2026-06-01 00:00:00
28,Cost account 3,Activity 9,2026-07-29 00:00:00,2026-08-04 00:00:00,NaN,NaN,2026-06-01 00:00:00
29,Cost account 4,None,None,None,NaN,0.0,2026-06-01 00:00:00
30,Cost account 4,Activity 10,2026-08-05 00:00:00,2026-08-18 00:00:00,NaN,NaN,2026-06-01 00:00:00
31,Cost account 4,Activity 11,2026-08-05 00:00:00,2026-08-11 00:00:00,NaN,NaN,2026-06-01 00:00:00

In [ ]:
import pandas as pd
import sqlite3

conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_05 = """
SELECT *
FROM COA_monthly_pv_table
"""
df_pv_phased = pd.read_sql_query(query_05, conn)
conn.close()
# rename columns
df_pv_phased.rename(columns={
    'Data_Date': 'Period',
    'evm_type': 'Metric',
    'EVM_value': 'Value'
}, inplace=True)

# Append Dataframes

df_combined = pd.concat([melted, df_pv_phased], ignore_index=True)

df_combined

               COA               Period     Metric          Value
0   Cost account 1  2026-05-01 00:00:00  EV_period  118000.000000
1   Cost account 1  2026-06-01 00:00:00  EV_period  104000.000000
2   Cost account 2  2026-05-01 00:00:00  EV_period       0.000000
3   Cost account 2  2026-06-01 00:00:00  EV_period       0.000000
4   Cost account 3  2026-05-01 00:00:00  EV_period       0.000000
5   Cost account 3  2026-06-01 00:00:00  EV_period       0.000000
6   Cost account 4  2026-05-01 00:00:00  EV_period       0.000000
7   Cost account 4  2026-06-01 00:00:00  EV_period       0.000000
8   Cost account 1  2026-05-01 00:00:00  AC_period  127440.000000
9   Cost account 1  2026-06-01 00:00:00  AC_period  112320.000000
10  Cost account 2  2026-05-01 00:00:00  AC_period       0.000000
11  Cost account 2  2026-06-01 00:00:00  AC_period       0.000000
12  Cost account 3  2026-05-01 00:00:00  AC_period       0.000000
13  Cost account 3  2026-06-01 00:00:00  AC_period       0.000000
14  Cost account 4  2026-05-01 00:00:00  AC_period       0.000000
15  Cost account 4  2026-06-01 00:00:00  AC_period       0.000000
16  Cost account 1  2026-05-01 00:00:00         pv  118461.538462
17  Cost account 1  2026-06-01 00:00:00         pv  133907.692308
18  Cost account 1  2026-07-01 00:00:00         pv   45230.769231
19  Cost account 2  2026-07-01 00:00:00         pv  168000.000000
20  Cost account 2  2026-08-01 00:00:00         pv  120817.307692
21  Cost account 2  2026-09-01 00:00:00         pv  211682.692308
22  Cost account 3  2026-07-01 00:00:00         pv    1666.666667
23  Cost account 3  2026-08-01 00:00:00         pv   63833.333333
24  Cost account 4  2026-08-01 00:00:00         pv  262500.000000

## Send to the dataframe

In [34]:
import sqlite3

table_name = "COA_monthly_evm_table"
print(table_name)

# Connect
conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')
cursor = conn.cursor()

# Drop table
cursor.execute(f"DROP TABLE IF EXISTS {table_name}")

# Write DataFrame
df_combined.to_sql(table_name, conn, if_exists='replace', index=False)

# Close
conn.close()

COA_monthly_evm_table

## Debug the script before reading it in Power BI

In [35]:
import pandas as pd
import sqlite3
from datetime import timedelta  # <-- needed for date_range with Timedelta or you can use freq='D'

conn = sqlite3.connect(r'C:\Users\efloresmendoza\OneDrive - John Holland Group\2024\140_Erick\01_database\01.-COST ACCOUNTING\ROsample.db')

# Define the SQL query
query_06 = """
SELECT *
FROM COA_monthly_evm_table

"""

df_evm_phased = pd.read_sql_query(query_06, conn)
conn.close()
df_evm_phased

               COA               Period     Metric          Value
0   Cost account 1  2026-05-01 00:00:00  EV_period  118000.000000
1   Cost account 1  2026-06-01 00:00:00  EV_period  104000.000000
2   Cost account 2  2026-05-01 00:00:00  EV_period       0.000000
3   Cost account 2  2026-06-01 00:00:00  EV_period       0.000000
4   Cost account 3  2026-05-01 00:00:00  EV_period       0.000000
5   Cost account 3  2026-06-01 00:00:00  EV_period       0.000000
6   Cost account 4  2026-05-01 00:00:00  EV_period       0.000000
7   Cost account 4  2026-06-01 00:00:00  EV_period       0.000000
8   Cost account 1  2026-05-01 00:00:00  AC_period  127440.000000
9   Cost account 1  2026-06-01 00:00:00  AC_period  112320.000000
10  Cost account 2  2026-05-01 00:00:00  AC_period       0.000000
11  Cost account 2  2026-06-01 00:00:00  AC_period       0.000000
12  Cost account 3  2026-05-01 00:00:00  AC_period       0.000000
13  Cost account 3  2026-06-01 00:00:00  AC_period       0.000000
14  Cost account 4  2026-05-01 00:00:00  AC_period       0.000000
15  Cost account 4  2026-06-01 00:00:00  AC_period       0.000000
16  Cost account 1  2026-05-01 00:00:00         pv  118461.538462
17  Cost account 1  2026-06-01 00:00:00         pv  133907.692308
18  Cost account 1  2026-07-01 00:00:00         pv   45230.769231
19  Cost account 2  2026-07-01 00:00:00         pv  168000.000000
20  Cost account 2  2026-08-01 00:00:00         pv  120817.307692
21  Cost account 2  2026-09-01 00:00:00         pv  211682.692308
22  Cost account 3  2026-07-01 00:00:00         pv    1666.666667
23  Cost account 3  2026-08-01 00:00:00         pv   63833.333333
24  Cost account 4  2026-08-01 00:00:00         pv  262500.000000

## ETC and EV togo

In [ ]:

# Set the start of the upcoming month
End_period = '30/06/2026'
public_holidays = pd.to_datetime([
    '2026-01-01',  # New Year’s Day
    '2026-04-02',  # Maundy Thursday
    '2026-04-03',  # Good Friday
    '2026-05-01',  # Labour Day
    '2026-06-07',  # Battle of Arica & Flag Day (often observed together)
    '2026-06-29',  # Saints Peter and Paul
    '2026-07-23',  # Air Force Day
    '2026-07-28',  # Independence Day
    '2026-07-29',  # Independence Day (second day)
    '2026-08-06',  # Battle of Junín
    '2026-08-30',  # Santa Rosa de Lima
    '2026-10-08',  # Battle of Angamos
    '2026-11-01',  # All Saints’ Day
    '2026-12-08',  # Immaculate Conception
    '2026-12-09',  # Battle of Ayacucho
    '2026-12-25',  # Christmas Day
])